#!/usr/bin/env bash
# ==============================================================================
# Sentinel-AutoGen-Hunter Host Enforcer Script
# ==============================================================================
# Description: Safely polls the append-only containment queue generated by
#              the unprivileged AI container and enforces iptables drops on
#              the DOCKER-USER chain to block lateral attacker traffic.
# ==============================================================================

set -euo pipefail

ACTION_FILE="${ACTION_LOG_PATH:-actions/pending_blocks.log}"
LOCK_FILE="/tmp/hunter_enforcer.lock"

# Simple lock mechanism to prevent race conditions
exec 200>"$LOCK_FILE"
flock -n 200 || exit 1

if [ ! -f "$ACTION_FILE" ]; then
    exit 0
fi

# Ensure DOCKER-USER chain exists (Docker initializes this by default)
if ! iptables -L DOCKER-USER -n >/dev/null 2>&1; then
    echo "[!] DOCKER-USER chain not found. Creating standard chain..."
    iptables -N DOCKER-USER || true
fi

# Process entries line by line: TIMESTAMP,IP,RISK,COMMAND
TEMP_FILE=$(mktemp)
mv "$ACTION_FILE" "$TEMP_FILE"
touch "$ACTION_FILE"

while IFS=',' read -r timestamp ip risk command || [ -n "$timestamp" ]; do
    # Skip empty lines or header
    if [ -z "$ip" ]; then
        continue
    fi

    # Strictly validate IPv4 format to prevent shell injection on the host
    if [[ ! "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        echo "[ERROR] Invalid IP format detected: $ip. Skipping for safety."
        continue
    fi

    echo "[+] [$timestamp] Enforcing containment for $ip (Risk: $risk)"

    # Check if rule already exists to maintain strict idempotency
    if iptables -C DOCKER-USER -s "$ip" -j DROP 2>/dev/null; then
        echo "    [-] Rule for $ip already present in DOCKER-USER chain. Skipping duplicate."
    else
        # Insert at the top of DOCKER-USER to drop packets before container routing
        iptables -I DOCKER-USER 1 -s "$ip" -j DROP
        echo "    [✓] Successfully inserted DROP rule in DOCKER-USER for $ip"
    fi

done < "$TEMP_FILE"

rm -f "$TEMP_FILE"
